### ISSUE TITLE
Filtering case sensitive

### ISSUE THREAD

**Issue by styfle** [bevacqua/horsey#11]
Is it intentional for the default filter to only match lowercase letters?
It works fine when users are typing because they typically don't use shift.
The problem is once an option is selected, deleting a character will no longer match.

## Example 

1. Initialize `horsey` with the following suggestions

```js
horsey(document.querySelector('input'), {
  suggestions: ['0P.06.0QU', '0S.06.0QU', '0T.06.0QU']
});
```

2. Type `q`
3. You'll see the all three options
4. Select an option
5. The input is populated with the text
6. Delete the last character (in this case `U`)
7. No suggestions popup anymore

I spent about an hour trying to find if this was a bug in horsey failing to show the matches.
But it looks like the problem is just the case sensitivity :disappointed: 

I realize I can change the default filter function which is my solution.
However this might turn off new users since it not obvious why it doesn't work as expected.

**Comment by bevacqua** [comment]
You are correct in that this line https://github.com/bevacqua/horsey/blob/master/horsey.js#L413 should lower case for `q` as well. Can you submit a PR?

Thanks for reporting this

**Comment by styfle** [comment]
I'll give it shot.
