### ISSUE TITLE
Performance for large datasets

### ISSUE THREAD

**Issue by styfle** [bevacqua/horsey#13]
I noticed that the implementation for the hide/show is just adding a class `sey-hide`.
This can get really slow for large datasets because changing the DOM is quite slow.
It also flashes the entire list upon typing the first letter before hiding items in the list that match.
I believe the performance can be improved dramatically if you do lazy rendering of the items such as [select2](https://github.com/select2/select2) or [slickgrid](https://github.com/mleibman/SlickGrid).

The downside would be a rigid height for each item in the list in order to calculate the position when scrolling. Maybe we can ignore the scrolling and instead switch to lazy rendering if a `limit` is imposed.
I can create a jsfiddle with an example of 1000+ items and then see if a lazy rendering solution performs better.

Are you interested or is this outside the scope of horsey?

**Comment by bevacqua** [comment]
Sounds interesting, I definitely want to fix the flicker issue you've mention

**Comment by styfle** [comment]
I almost have a working example to show the performance enhancement:

Before: https://jsfiddle.net/nj4qx19a/2/embedded/result/
After: https://jsfiddle.net/nj4qx19a/3/embedded/result/

Try typing "john" quickly in each input and you should notice a difference.
This also fixes the flash/flicker on initial load.

I'm still working on a up/down selection which stopped working for some reason. Once I fix that bug I can submit a pull request but I might need some help tracking it down.

**Comment by bevacqua** [comment]
Not sure what your changes were. Can you put them up on a PR? Thanks.
