### ISSUE TITLE
Live suggestion list

### ISSUE THREAD

**Issue by gaydenko** [bevacqua/horsey#18]
Hi! README.md contains:

> Here's how you would lazy load your suggestions, except, you know, using actual AJAX calls. Note that this method is called a single time.

Does it mean the library doesn't suit use cases a suggestions list must be rebuilt on every input event (that is the cases with, say, million suggestions, and to form a limited list of most suitable items for every search term change is a server-side task)?

**Comment by bevacqua** [comment]
Not right now, but I'd like to support that use case

**Comment by gaydenko** [comment]
> I'd like to support that use case

So, will we let the issue to be open for now?

**Comment by bevacqua** [comment]
Yes. Feel free to contribute a PR to this effect

**Comment by FND** [comment]
FWIW, I've tried implementing this, but it proved trickier than expected - probably because I don't fully understand how the various pieces are intertwined.

A fugly (and incomplete) hack is as far as I got before escaping the rabbit hole:

```diff
diff --git a/horsey.js b/horsey.js
index 8044a47..2e87d64 100644
--- a/horsey.js
+++ b/horsey.js
@@ -247,7 +247,16 @@ function horsey (el, options) {
     crossvent.fabricate(attachment, 'horsey-hide');
   }
 
-  function keydown (e) {
+  function keydown (e, immediate) {
+    if(!immediate) {
+      suggestions(function(results) {
+        loaded(results);
+        keydown(e, true);
+        show();
+      });
+      return;
+    }
+
     var shown = visible();
     var which = e.which || e.keyCode;
     if (which === KEY_DOWN) {
```

**Comment by bevacqua** [comment]
Introduced in `3.0.0`
