### ISSUE TITLE
IE11: Entries not selectable by clicking

### ISSUE THREAD

**Issue by meodai** [bevacqua/horsey#23]
On IE11 it is not possible to select entries in the dropdown be clicking: The dropdown disappears, but the textfield gets no value. I could reproduce this in my project and in every horsey demo.

Selecting them with the keyboard works perfectly.

PS: Looks like clickedSuggestion never get triggered `crossvent.add(li, 'click', clickedSuggestion);` replacing this by `li.addEventListener('click', clickedSuggestion)` does not change the deal. So I don't think that it is a crossvent issue.

Maybe related to this?: https://github.com/walmartlabs/thorax/issues/299

**Comment by fhelsana** [comment]
It works for me when I set autoHideOnBlur to false.

**Comment by backflip** [comment]
Having the same issue. Using `pointerdown` when available would be an option:
`var clickEvent = ('onpointerdown' in window) ? 'pointerdown' : 'click';`

**Comment by bevacqua** [comment]
This should be fixed in latest
