### ISSUE TITLE
Allow different elements for list items

### ISSUE THREAD

**Issue by TehShrike** [bevacqua/horsey#25]
Would you accept a pull request to add an option for list item elements so that they could be something other than a `li` element?

https://github.com/bevacqua/horsey/blob/master/horsey.js#L129

I'm using Bootstrap and would like to use a [list group of links](http://getbootstrap.com/components/#list-group-linked), which requires the items to be `a` elements.

**Comment by bevacqua** [comment]
Sorry, no.
