### ISSUE TITLE
Disallow input values if not in the provided suggestions

### ISSUE THREAD

**Issue by mrmartineau** [bevacqua/horsey#29]
Is it possible to disallow input values if not in the provided suggestions? I see there is a `.filter()` method but I don't think I want to overwrite the default functionality, is that what I should use? Does anyone have any idea how to achieve this?

If my suggestions were like this:
```js
suggestions: ['sports', 'drama', 'romantic comedy', 'science fiction', 'thriller']
```

and a user tried to add `action` as a field value, I would like to disallow that.

**Comment by bevacqua** [comment]
See `free` option.
