### ISSUE TITLE
How can I avoid the style left and top of sey-list

### ISSUE THREAD

**Issue by wbotelhos** [bevacqua/horsey#31]
I trying to use `appendTo` to point to a fixed place into my template. This target is a sub wrapper, so I can use `width: 100%` to be equal the parents.

```html
<div  class="search-box" style="width: 48%">
  <input type="text" style="width: 100%">
  <div  class="target">
    <ul style="left: 250px; top: 256px; width: 100%;"> <!-- I want just width: 100% here -->
    </ul>
  </div>
</div>
```

Any solution over `!important`?

**Comment by bevacqua** [comment]
Sorry, I'll need a demo. Closing for now.

**Comment by wbotelhos** [comment]
It is, even I use the option `appendTo`, the wrapper 'sey-container' keep the style `left` and `top`. But if I'm using a container, probably I don't want to use an absolute element. Maybe avoid this `style` tag is a cleaner thing, since I won't need to reset it.
