### ISSUE TITLE
Keyboard arrow does not navigates over all suggestions matched on backend

### ISSUE THREAD

**Issue by wbotelhos** [bevacqua/horsey#33]
Actually I search the same query into two field on database: `name` or `email`, but on `getText` I need to choose one field of `suggestion` JSON. There is some way to the navigation goes over all items based on one match or another?

In the same way I would like to highlight the both text:

John **Doe**
**doe**`@`john**doe**.org

See my question on: https://github.com/bevacqua/horsey/issues/32

One solutions was concat the strings I want to navigate:

```js
getText: function(object) {
  return object.name + object.email;
}
```

So the keyboard can do the "`indexOf`" in some position. Bad, no?

Any options to choose more than on field inside the returned JSON?

**Comment by bevacqua** [comment]
There's many new options that you can use to fix this stuff. Highlighting is now on by default.
