### ISSUE TITLE
sey-list incorrectly positioned when using appendTo

### ISSUE THREAD

**Issue by josephschmitt** [bevacqua/horsey#35]
If you use the appendTo function to append the sey-list to something other than document.body, the left and right properties of the list are being set as if the list was still being appended directly to the body. This is easiest to see if you position an element that wraps the input field somewhere on the page, then set appendTo to point to that element. You'll notice top and left are being set to the position of that wrapper, but since the list is inside that wrapper, it ends up getting offset. Example:

http://cl.ly/fPjk
http://plnkr.co/HhRlVL5RNaZwDzwistkc

**Comment by josephschmitt** [comment]
I would expect top and left values to be relative to the element being appended to, not to the body when appendTo is set.

**Comment by bevacqua** [comment]
Should be fixed now.

**Comment by msokk** [comment]
Top value is correct with `appendTo`, but left value is still calculated from body for some reason.

**Comment by msokk** [comment]
Aha, bullseye only applies context to `top` - https://github.com/bevacqua/bullseye/blob/master/bullseye.js#L76
