### ISSUE TITLE
Make `defaultFilter` publicly available (somehow?)

### ISSUE THREAD

**Issue by domchristie** [bevacqua/horsey#4]
Use case: use default filter method, with some additional conditions. For example, prevent suggesting previously used tags, it’d be nice to do something like:

    filter: function (q, suggestion) {
      return !_this.insignia.tags().includes(suggestion) && this._super.apply(this, arguments);
    }

**Comment by domchristie** [comment]
(Actually this example may be better solved with a `.remove(suggestion)` method?)

**Comment by bevacqua** [comment]
You can remove them as documented holding on to the element reference in .add, but exposing the default filter makes sense. pulls welcome

**Comment by domchristie** [comment]
> You can remove them as documented holding on to the element reference in .add

Unfortunately I don’t have references to items added using the `suggestions` option :/

**Comment by bevacqua** [comment]
Exposed in `1.2.0`

**Comment by domchristie** [comment]
Great, thanks!
