### ISSUE TITLE
Incorrect position of autocomplete box

### ISSUE THREAD

**Issue by Hurtak** [bevacqua/horsey#5]
Autocomplete box should be right under input, on blank page with default settings top position is incorrectly calculated.

Firefox 39, Chrome 43

http://i.imgur.com/iwndgNi.png

**Comment by bevacqua** [comment]
That loOks like the default margin for ul elements. Just do margin: 0

**Comment by Hurtak** [comment]
Thanks, this worked. What confused me was that on demo page the suggest box was right under input and I just assumed you are using default stylesheet there.
I think `margin: 0` should be part of default stylesheet inside `.sey-list`. If you are interested, I can create pull request.

**Comment by bevacqua** [comment]
Sure
