### ISSUE TITLE
Options for styling

### ISSUE THREAD

**Issue by disciple-dev** [bevacqua/horsey#55]
Hi great library you have, here!

One thing I'm having trouble with is styling: there does not seem to be much flexibility. Perhaps I'm totally missing something, but it would be helpful to pass in some classes, at the least.

**Comment by bevacqua** [comment]
You seem to be! Have you looked at `renderItem` and `renderCategory`? Those give you direct access to DOM elements you can style. Aslo there's default classes for most elements.

**Comment by iwritesomecode** [comment]
I was thinking it would be helpful to be able to specify classes for the `sey-container` and `set-categories` divs, especially if you had more than one of them initialised at the same.
