### ISSUE TITLE
How to use Events of horsey instance? 

### ISSUE THREAD

**Issue by YozhEzhi** [bevacqua/horsey#56]
For example `horsey-show`.
I want to use some callback after user search.

**Comment by nsdifficult** [comment]
I also met this problem, Did you solve it ? Thanks

**Comment by YozhEzhi** [comment]
@nsdifficult Nope.

**Comment by nsdifficult** [comment]
@YozhEzhi

**Comment by iasinov** [comment]
@YozhEzhi @nsdifficult Regarding to the events, they are being emitted on the provided element
`new Horsey(el, {}); 
el.addEventListener('horsey-show', ()=>{console.log('show')});`
