### ISSUE TITLE
How to limit number of results?

### ISSUE THREAD

**Issue by Hurtak** [bevacqua/horsey#7]
If i have larger number of suggestions, how do i limit how much of suggestions are displayed in rendered box?

**Comment by bevacqua** [comment]
By filtering out and cutting after x results.

**Comment by Hurtak** [comment]
Hi, i am having some trouble implementing it, could you maybe provide code snippet? Thanks.

**Comment by bevacqua** [comment]
```js
function horsefy (el) {
  var i = 0, max = 50;
  return horsey(el, {
    filter: function () {
      return i++ < max;
    }
  });
}
```

**Comment by Hurtak** [comment]
This overwrites default filtering which uses fuzzysearch with my own function which just displays first x results. How do i just filter first x results without overwriting default filtering function? Also your function doesn't reset `i` to `0` so it only works first time i type.

**Comment by bevacqua** [comment]
It was just an example. You can deduce how to do the rest yourself, or submit a PR that does it in core

**Comment by bevacqua** [comment]
You can now use the `limit` option
