### ISSUE TITLE
Wrong suggestions ?

### ISSUE THREAD

**Issue by ujc** [bevacqua/horsey#9]
Why am getting 'Bananas' and 'Oranges' suggested when I enter the text "ornfs" ?
(the input text is just an experiment, I'm getting weird results on similar text while trying out the examples on the site)

EDIT: This only seems to happen when "key:value" is used. For "array of strings" suggestions are OK.

![image](https://cloud.githubusercontent.com/assets/5549335/8655397/7e459868-2999-11e5-891d-1602beda954b.png)

*I'm actually very impressed with this library. Looking forward to see how to fix this issue

**Comment by bevacqua** [comment]
Because of fuzzy searching. All those letters are found, in order, in the results

https://github.com/bevacqua/horsey#filter

**Comment by ujc** [comment]
Oh! I completely missed that (sorry!)
That's even better (;

Thx!
